FROM node:18-alpine
WORKDIR /usr/src/app

# Install runtime deps
COPY package.json package-lock.json* ./
RUN npm install --production

# Copy app
COPY . .

ENV NODE_ENV=production
EXPOSE 3000
CMD ["node", "backend/server.js"]
